baseURL = 'https://utility-foundation.github.io/'
languageCode = 'en-us'
title = 'Utility Foundation'
theme = "codex"
[params]
github = "https://github.com/Utility-Foundation/Utility-Foundation.github.io"
